#!/bin/sh

appendpath () {
    case ":$PATH:" in
        *:"$1":*)
            ;;
        *)
            PATH="${PATH:+$PATH:}$1"
    esac
}

HOMEBREW_PREFIX=${HOMEBREW_PREFIX:-"/usr/local"}

#     /usr/local
[ -d "$HOMEBREW_PREFIX/bin" ] && appendpath "$HOMEBREW_PREFIX/bin"
[ -d "$HOMEBREW_PREFIX/sbin" ] && appendpath "$HOMEBREW_PREFIX/sbin"
[ -d "$HOMEBREW_PREFIX/share/info" ] && MANPATH="$MANPATH:$HOMEBREW_PREFIX/share/info"
[ -d "$HOMEBREW_PREFIX/share/infopath" ] && INFOPATH="$INFOPATH:$HOMEBREW_PREFIX/share/infopath"

#     llvm
[ -d "$HOMEBREW_PREFIX/opt/llvm/bin" ] && appendpath "$HOMEBREW_PREFIX/opt/llvm/bin"
[ -d "$HOMEBREW_PREFIX/opt/ccache/libexec" ] && appendpath "$HOMEBREW_PREFIX/opt/ccache/libexec"

#     curl
[ -d "$HOMEBREW_PREFIX/opt/curl" ] && appendpath "$HOMEBREW_PREFIX/opt/curl/bin"

unset appendpath
export PATH
export MANPATH="$MANPATH"
export INFOPATH=":$INFOPATH"
