#!/bin/sh

HOMEBREW_PREFIX=${HOMEBREW_PREFIX:-"/usr/local"}
[ -f "$HOMEBREW_PREFIX/bin/brew" ] || return 0

pathmunge () {
  case ":${PATH}:" in
    *:"$1":*)
      ;;
    *)
      if [ "$2" = "after" ] ; then
        PATH="${PATH:+"$PATH:"}$1"
      else
        PATH="$1${PATH:+":$PATH"}"
      fi
  esac
}

#     /usr/local
pathmunge "$HOMEBREW_PREFIX/bin"
pathmunge "$HOMEBREW_PREFIX/sbin"
MANPATH="$MANPATH:$HOMEBREW_PREFIX/share/info"
INFOPATH="$INFOPATH:$HOMEBREW_PREFIX/share/infopath"

#     llvm
pathmunge "$HOMEBREW_PREFIX/opt/llvm/bin"
pathmunge "$HOMEBREW_PREFIX/opt/ccache/libexec"

#     curl
pathmunge "$HOMEBREW_PREFIX/opt/curl/bin"

unset pathmunge

export HOMEBREW_PREFIX
export PATH
export MANPATH
export INFOPATH
