#!/usr/bin/env zsh
# /etc/zprofile on macOS loads /usr/libexec/path_helper which overwrites PATH
# disable it
# setopt no_global_rcs

# -------------
# gpg ssh agent
# -------------
if (( $+commands[gpgconf] )) ; then
  unset SSH_AGENT_PID
  if [[ -v SSH_AUTH_SOCK && "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]]; then
    export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
  fi
fi
if (( $+commands[gpg-connect-aggent] )) ; then
  if [[ -v SSH_AUTH_SOCK ]]; then
    export GPG_TTY=$(tty)
    echo "UPDATESTARTUPTTY" | gpg-connect-agent > /dev/null 2>&1
  fi
fi

# not needed because we use .plist hack
# https://evilmartians.com/chronicles/stick-with-security-yubikey-ssh-gnupg-macos
# eval "$(gpg-agent --daemon --enable-ssh-support)"
