# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd extendedglob
unsetopt beep
bindkey -v
# End of lines configured by zsh-newuser-install

source ~/.config/zsh/antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# robbyrussell's oh-my-zsh :: Productivity
antigen bundle colored-man          # colored manpages
antigen bundle colorize             # cat with syntax highlighting
antigen bundle command-not-found    # suggests package name with relevant command
antigen bundle cp                   # cp with progress bar (rsync)
antigen bundle ssh-agent            # ssh-agent start script
antigen bundle vi-mode

# robbyrussell's oh-my-zsh :: Build tools
antigen bundle git                  # git aliases
antigen bundle github               # cli access, url shortener

# robbyrussell's oh-my-zsh :: Python
antigen bundle pip

# Misc tools
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle tarruda/zsh-autosuggestions
antigen bundle chrissicool/zsh-256color
antigen bundle djui/alias-tips

# Load the theme.
# oh-my-zsh :: mrtazz blinks norm
antigen theme norm

# Tell antigen that you're done.
antigen apply

# Enable autosuggestions automatically.
zle-line-init() {
    zle autosuggest-start
}
zle -N zle-line-init
